spring:
  application:
    name: fintech
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/translator}
    username: ${JDBC_USERNAME:postgres}
    password: ${JDBC_PASSWORD:gbhfns}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/dbchangelog.xml

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true

translator:
  url: ${API_URL:http://localhost:5000/translate}